### ISSUE TITLE
Angelfish: Compilation failure with gcc-6 and GLIBC 2.24

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#107]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 107
Date: 2016-10-20 08:22:30 +0200
From: Antero Nousiainen &lt;<antero.nousiainen@nokia.com>&gt;
To:   openfastpath@list.openfastpath.org
CC:   sorin.vultureanu@enea.com

Last updated: 2016-11-22 13:55:24 +0100

## Bugzilla Comment ID: 195
Date: 2016-10-20 08:22:30 +0200
From: Antero Nousiainen &lt;<antero.nousiainen@nokia.com>&gt;

The Angelfish branch fails to compile with gcc-6 and GLIBC 2.24 with the following error message:

In file included from /usr/include/linux/if_tunnel.h:6:0,
                 from ofp_netlink.c:16:
/usr/include/linux/ip.h:85:8: error: redefinition of ‘struct iphdr’
 struct iphdr {
        ^~~~~
In file included from ofp_netlink.c:12:0:
/usr/include/netinet/ip.h:44:8: note: originally defined here
 struct iphdr
        ^~~~~

The compilation worked still with gcc-5 and GLIBC 2.23. The compilation problem is introduced by a change in /usr/include/linux/if_tunnel.h:

@@ -2,6 +2,9 @@
 #define _IF_TUNNEL_H_
 
 #include <linux/types.h>
+#include <linux/if.h>
+#include <linux/ip.h>
+#include <linux/in6.h>
 #include <asm/byteorder.h>

To fix this the following change is needed in src/ofp_netlink.c:

@@ -9,7 +9,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <netinet/in.h>
-#include <netinet/ip.h>
+#include <linux/ip.h>
 #include <linux/netlink.h>
 #include <linux/rtnetlink.h>
 #include <linux/if_arp.h>

The fix has already been pushed to master in a0a4c46.

## Bugzilla Comment ID: 203
Date: 2016-11-22 13:46:28 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Can we close this thing?

## Bugzilla Comment ID: 204
Date: 2016-11-22 13:55:24 +0100
From: Antero Nousiainen &lt;<antero.nousiainen@nokia.com>&gt;

(In reply to Sorin Vultureanu from comment #1)
> Can we close this thing?

This is still yet to be fixed on Angelfish branch, I'm still getting the same compilation error. The fix from master should be merged to Angelfish to fix this.

**Comment by JereLeppanen** [comment]
Fix cherry picked to angelfish as commit 9e12fc4 and included in 2.0.1.
